### ISSUE TITLE
The URL is not changing by redirect

### ISSUE THREAD

**Issue by pawelangelow** [ChaosGroup/redux-saga-first-router#1]
Hi!

The problem scenario is: application with few routes ("/foo", "/bar", etc...) and I want to add route "/" which loads the "foo" screen i.e. "/foo" and "/" both open same screen. 

```js
const routesMap = buildRoutesMap(
	route('FOO', '/foo', fooSaga),
	route('BAR', '/bar', barSaga),
	route('_INDEX_', '/', rootSaga)
);
```

So I've added route "/", which activates saga.

```js
function* rootSaga() {
	yield put(navigate('FOO'));
}
```

It loads "foo" screen, respectively it **activates the fooSaga**, but the URL is still "/". If saga looks like this:

```js
function* rootSaga() {
	yield call(delay, 1);
	yield put(navigate('FOO'));
}
```
the URL is changed.

**Comment by sachmata** [comment]
Thank you @pawelangelow, good find!  I am reproducing it, it looks like a race condition between router internal sagas and attached 'per route' saga.

**Comment by sachmata** [comment]
https://github.com/ChaosGroup/redux-saga-first-router/commit/81256ac1377c0adc18d3dbe07f9dbbf4ed73f613 Fix saga initialization order mismatch
